apiVersion: apps/v1
kind: Deployment
metadata:
  name: webform-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webform
  template:
    metadata:
      labels:
        app: webform
    spec:
      containers:
      - name: webform-container
        image: sanaqvi573/webform-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webform-service
spec:
  type: LoadBalancer
  selector:
    app: webform
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
